from langchain_chroma import Chroma
from langchain_openai import OpenAIEmbeddings

from vectorstores.utils import load_split_docs_pypdf


def get_chroma_vector_store(path):
    """
    Creates a Chroma vector store for document embeddings.

    This function loads documents from the specified path using `load_split_docs_pypdf`,
    then creates a Chroma vector store with embeddings generated by OpenAI's model.

    Args:
        path (str): The path to the documents that will be loaded and embedded.

    Returns:
        Chroma: An instance of the Chroma vector store containing document embeddings.
    """
    documents = load_split_docs_pypdf(path=path)
    vectorstore = Chroma.from_documents(
        documents=documents,
        embedding=OpenAIEmbeddings(model="text-embedding-3-small"),
    )

    return vectorstore
